USE [master]
GO
CREATE LOGIN [usuario] WITH PASSWORD=N'password', DEFAULT_DATABASE=[DAI-TP06], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE [DAI-TP06]
GO
CREATE USER [usuario] FOR LOGIN [usuario]
GO
USE [DAI-TP06]
GO
ALTER ROLE [db_owner] ADD MEMBER [usuario]
GO